//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod tb_article;
pub mod tb_article_category;
pub mod tb_permission;
pub mod tb_role;
pub mod tb_role_permission;
pub mod tb_user;
