//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tb_role_permission")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub role_id: i32,
    pub permission_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tb_permission::Entity",
        from = "Column::PermissionId",
        to = "super::tb_permission::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TbPermission,
    #[sea_orm(
        belongs_to = "super::tb_role::Entity",
        from = "Column::RoleId",
        to = "super::tb_role::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TbRole,
}

impl Related<super::tb_permission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbPermission.def()
    }
}

impl Related<super::tb_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbRole.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
