//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tb_role")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::tb_role_permission::Entity")]
    TbRolePermission,
}

impl Related<super::tb_role_permission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TbRolePermission.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
